name: 'pull-request-details'
description: 'Action to get details related to a pull request which are not available all the events published to trigger workflows'
branding:
  icon: 'check'
  color: 'green'
author: 'sakhnovict,ihtkas'
inputs:
  approvalsCount:
    description: 'The number of unique approvals to set isApproved as true.'
    default: '1'
  onlyEqual:
    description: 'If true then isApproved = true, only when the number of approvals equal approvalsCount.'
    default: 'false'
outputs:
  isApproved:
    description: 'If current PR is approved the right number of times, this value is set as true.'
runs:
  using: 'node16'
  main: 'dist/index.js'
